import {  COLORS, COMPRESSION_ALGORITHM, IMG_REPRESENTATION } from "@/utils/compressao-imagens";

export const imagePaisagem = {
  4:
  [COLORS.YELLOW, COLORS.SKY, COLORS.SKY, COLORS.SKY,
    COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY,
    COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN,
    COLORS.GREEN, COLORS.RED, COLORS.GREEN, COLORS.GREEN,
  ],
  8: 
  [COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY,
    COLORS.SKY, COLORS.YELLOW, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY,
    COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY,
    COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY,
    COLORS.SKY, COLORS.GREEN, COLORS.GREEN, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.GREEN, COLORS.SKY,
    COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN,
    COLORS.GREEN, COLORS.RED, COLORS.GREEN, COLORS.RED, COLORS.GREEN, COLORS.RED, COLORS.GREEN, COLORS.GREEN,
    COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN,
  ],
  12: 
  [COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY,
    COLORS.SKY, COLORS.YELLOW, COLORS.YELLOW, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY,
    COLORS.SKY, COLORS.YELLOW, COLORS.YELLOW, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY,
    COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY,
    COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY,
    COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY,
    COLORS.SKY, COLORS.SKY, COLORS.GREEN, COLORS.GREEN, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY,
    COLORS.SKY, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.GREEN, COLORS.GREEN,
    COLORS.GREEN, COLORS.GREEN, COLORS.RED, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.SKY, COLORS.SKY, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN,
    COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.RED, COLORS.GREEN, 
    COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.RED, COLORS.GREEN, COLORS.GREEN, COLORS.RED, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, 
    COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, 
  ]
}

export const imageListras = {
4:
[COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED,
  COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN,
  COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY,
  COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE,
],
8:
[COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED,
  COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN,
  COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY,
  COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE,
  COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED,
  COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN,
  COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY,
  COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE,
],
12:
[COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED,
  COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN,
  COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY,
  COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE,  COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE,
  COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED,
  COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN,
  COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY,
  COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE,  COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE,
  COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED,
  COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN, COLORS.GREEN,
  COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY, COLORS.SKY,
  COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE,  COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE, COLORS.ORANGE,
]
}

export const imageDiagonais = {
4: 
[COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE,
  COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY,
  COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN,
  COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED,
],
8:
[COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE,
  COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY,
  COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN,
  COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED,
  COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE,
  COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY,
  COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN,
  COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED,
],
12:
[COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE,  COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE,
  COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY,  COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY,
  COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN,
  COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED,
  COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE,  COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE,
  COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY,  COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY,
  COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN,
  COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED,
  COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE,  COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE,
  COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY,  COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY,
  COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN,
  COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED, COLORS.GREEN, COLORS.SKY, COLORS.PURPLE, COLORS.RED,
]
}

export const model = [
  {
    id: "diagonal-huffman-8x8",
    algoritmo: COMPRESSION_ALGORITHM.HUFFMAN,
    desenho: "Diagonais",
    tamanho: "8",
    representacao: IMG_REPRESENTATION.COLORS
  },
  {
    id: "paisagem-rle-12x12",
    algoritmo:  COMPRESSION_ALGORITHM.RLE,
    desenho: "Paisagem",
    tamanho: "12",
    representacao: IMG_REPRESENTATION.BLACK_AND_WHITE
  },
  {
    id: "diagonal-lzw-4x4",
    algoritmo: COMPRESSION_ALGORITHM.LZW,
    desenho: "Diagonais",
    tamanho: "4",
    representacao: IMG_REPRESENTATION.GRAYSCALE
  },
  {
    id: "linha-rle-12x12",
    algoritmo: COMPRESSION_ALGORITHM.RLE,
    desenho: "Listras",
    tamanho: "12",
    representacao: IMG_REPRESENTATION.COLORS
  },

];